/* 
 * This file was generated by running
 *   $ pfsc license about pbe
 * in the pfsc-manage project.
 */
export const softwareTableRows = `


<!-- pfsc-browser-ext -->
<tr><td><a target="_blank"
href="https://github.com/proofscape/pbe/tree/v0.2.1">
pfsc-browser-ext
</a><span class="vers" data-proj-name="pfsc-browser-ext">
0.2.1
</span></td>
<td><a target="_blank"
href="https://github.com/proofscape/pbe/blob/v0.2.1/LICENSE">
Apache-2.0
</a></td></tr>

<!-- bootstrap -->
<tr><td><a target="_blank"
href="https://github.com/twbs/bootstrap/tree/v4.5.2">
bootstrap
</a><span class="vers" data-proj-name="bootstrap">
4.5.2
</span></td>
<td><a target="_blank"
href="https://github.com/twbs/bootstrap/blob/v4.5.2/LICENSE">
MIT
</a></td></tr>

<!-- bootswatch -->
<tr><td><a target="_blank"
href="https://github.com/thomaspark/bootswatch/tree/v4.5.2">
bootswatch
</a><span class="vers" data-proj-name="bootswatch">
4.5.2
</span></td>
<td><a target="_blank"
href="https://github.com/thomaspark/bootswatch/blob/v4.5.2/LICENSE">
MIT
</a></td></tr>

<!-- browser-peers -->
<tr><td><a target="_blank"
href="https://github.com/skieffer/browser-peers/tree/v0.2.0">
browser-peers
</a><span class="vers" data-proj-name="browser-peers">
0.2.0
</span></td>
<td><a target="_blank"
href="https://github.com/skieffer/browser-peers/blob/v0.2.0/LICENSE">
MIT
</a></td></tr>

<!-- jquery -->
<tr><td><a target="_blank"
href="https://github.com/jquery/jquery/tree/3.5.1">
jquery
</a><span class="vers" data-proj-name="jquery">
3.5.1
</span></td>
<td><a target="_blank"
href="https://github.com/jquery/jquery/blob/3.5.1/LICENSE.txt">
MIT
</a></td></tr>

<!-- lru-cache -->
<tr><td><a target="_blank"
href="https://github.com/isaacs/node-lru-cache/tree/v6.0.0">
lru-cache
</a><span class="vers" data-proj-name="lru-cache">
6.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/isaacs/node-lru-cache/blob/v6.0.0/LICENSE">
ISC
</a></td></tr>

<!-- popper.js -->
<tr><td><a target="_blank"
href="https://github.com/FezVrasta/popper.js/tree/v1.16.1">
popper.js
</a><span class="vers" data-proj-name="popper.js">
1.16.1
</span></td>
<td><a target="_blank"
href="https://github.com/floating-ui/floating-ui/blob/v1.16.1/LICENSE.md">
MIT
</a></td></tr>

<!-- webextension-polyfill -->
<tr><td><a target="_blank"
href="https://github.com/mozilla/webextension-polyfill/tree/0.6.0">
webextension-polyfill
</a><span class="vers" data-proj-name="webextension-polyfill">
0.6.0
</span></td>
<td><a target="_blank"
href="https://github.com/mozilla/webextension-polyfill/blob/0.6.0/LICENSE">
MPL-2.0
</a></td></tr>

<!-- websocket-driver -->
<tr><td><a target="_blank"
href="https://github.com/faye/websocket-driver-node/tree/0.7.4">
websocket-driver
</a><span class="vers" data-proj-name="websocket-driver">
0.7.4
</span></td>
<td><a target="_blank"
href="https://github.com/faye/websocket-driver-node/blob/0.7.4/LICENSE.md">
Apache-2.0
</a></td></tr>

<!-- yallist -->
<tr><td><a target="_blank"
href="https://github.com/isaacs/yallist/tree/v4.0.0">
yallist
</a><span class="vers" data-proj-name="yallist">
4.0.0
</span></td>
<td><a target="_blank"
href="https://github.com/isaacs/yallist/blob/v4.0.0/LICENSE">
ISC
</a></td></tr>

<!-- http-parser-js -->
<tr><td><a target="_blank"
href="https://github.com/creationix/http-parser-js">
http-parser-js
</a><span class="vers" data-proj-name="http-parser-js">
0.5.2
</span></td>
<td><a target="_blank"
href="https://github.com/creationix/http-parser-js/blob/master/LICENSE.md">
MIT
</a></td></tr>

<!-- safe-buffer -->
<tr><td><a target="_blank"
href="https://github.com/feross/safe-buffer/tree/v5.1.2">
safe-buffer
</a><span class="vers" data-proj-name="safe-buffer">
5.1.2
</span></td>
<td><a target="_blank"
href="https://github.com/feross/safe-buffer/blob/v5.1.2/LICENSE">
MIT
</a></td></tr>

<!-- websocket-extensions -->
<tr><td><a target="_blank"
href="https://github.com/faye/websocket-extensions-node/tree/0.1.4">
websocket-extensions
</a><span class="vers" data-proj-name="websocket-extensions">
0.1.4
</span></td>
<td><a target="_blank"
href="https://github.com/faye/websocket-extensions-node/blob/0.1.4/LICENSE.md">
Apache-2.0
</a></td></tr>
`;